name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  all:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm t

